name: threadable_better_player
description: Advanced video player, fork of better_player with upcoming modifications and continued support.
version: 1.0.0
# Disabled because of warning from analyzer
# authors:
#  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/threadable/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  wakelock: ^0.6.1+2
  meta: ^1.7.0
  flutter_widget_from_html_core: ^0.8.5+3
  visibility_detector: ^0.3.3
  path_provider: ^2.0.10
  collection: ^1.16.0
  xml: ^6.1.0

dev_dependencies:
  lint: ^1.8.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin