name: threadable_better_player
description: Advanced video player maintained by Threadable with continued Flutter, iOS, and Android support.
version: 2.1.0
homepage: https://github.com/threadable/betterplayer

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.17.0
  flutter_widget_from_html_core: ^0.17.2
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.5
  collection: ^1.19.1
  xml: ^6.6.1
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.threadable.betterplayer
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin
